/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package inicioSesion.gui;

import inicioSesion.Logica.LogicaCliente;
import inicioSesion.dto.client;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author estudiante
 */
public class FormularioRegistro extends javax.swing.JDialog {

    private static String pathImage;

    /**
     * Creates new form FormularioRegistro
     */
    public FormularioRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initButton();
        jButtonRegistro.setEnabled(false);
    }

    private void initButton() {
        RadioButtonSR.setActionCommand("Señor");
        RadioButtonSRA.setActionCommand("Señora");
    }

    private boolean validar() {
        // Validar que el nombre no esté vacío

        ValidationGroup group = validationPanel1.getValidationGroup();
        group.add(jTextFieldUser, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jPassField1, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jPassField2, StringValidators.REQUIRE_NON_EMPTY_STRING);

        if (!jPassField1.getText().equals(jPassField2.getText())) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden, verifique que las ha introducido correctamente.", "", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        // EJEMPLO VALIDACION DE FECHA CON CONVERSION (DATE -> STRING).
        
        /*SimpleDateFormat simpledate = new SimpleDateFormat("dd-MM-yyyy");
        String registro = simpledate.format(jDateRegistro.getDate());
        if (registro == null || name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La fecha de registro no puede estar vacia.");
            return false;
        }*/

        // Si pasa todas las validaciones, retornar true
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTrato = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelUser = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabelPass = new javax.swing.JLabel();
        jPassField1 = new javax.swing.JPasswordField();
        jLabelPass2 = new javax.swing.JLabel();
        jPassField2 = new javax.swing.JPasswordField();
        jLabelBirth = new javax.swing.JLabel();
        jComboBoxLocalidad = new javax.swing.JComboBox<>();
        jLabelImage = new javax.swing.JLabel();
        jButtonImg = new javax.swing.JButton();
        jLabelRegistro = new javax.swing.JLabel();
        jDateRegistro = new com.toedter.calendar.JDateChooser();
        jLabelTerms = new javax.swing.JLabel();
        jCheckTerminos = new javax.swing.JCheckBox();
        jLabelAge = new javax.swing.JLabel();
        jSpinnerAge = new javax.swing.JSpinner();
        jButtonRegistro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RadioButtonSR = new javax.swing.JRadioButton();
        RadioButtonSRA = new javax.swing.JRadioButton();
        jButtonHelp = new javax.swing.JButton();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));

        jPanel1.setForeground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new java.awt.GridLayout(9, 2, 0, 10));

        jLabelUser.setText("Usuario: ");
        jPanel1.add(jLabelUser);
        jPanel1.add(jTextFieldUser);

        jLabelPass.setText("Contraseña: ");
        jPanel1.add(jLabelPass);

        jPassField1.setText("jPasswordField1");
        jPanel1.add(jPassField1);

        jLabelPass2.setText("Repite Contraseña:");
        jPanel1.add(jLabelPass2);

        jPassField2.setText("jPasswordField2");
        jPassField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jPassField2);

        jLabelBirth.setText("Lugar de nacimiento: ");
        jPanel1.add(jLabelBirth);

        jComboBoxLocalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Albacete", "Barcelona", "Cuenca", "Granada", "Las Palmas", "Madrid", "S.Cruz Tenerife", "Toledo", "Valencia ", "Zaragoza" }));
        jComboBoxLocalidad.setAlignmentX(0.0F);
        jComboBoxLocalidad.setAlignmentY(0.0F);
        jPanel1.add(jComboBoxLocalidad);

        jLabelImage.setText("Imágen: ");
        jPanel1.add(jLabelImage);

        jButtonImg.setText("Seleccione...");
        jButtonImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImgActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonImg);

        jLabelRegistro.setText("Fecha Registro: ");
        jPanel1.add(jLabelRegistro);
        jPanel1.add(jDateRegistro);

        jLabelTerms.setText("Términos y condiciones: ");
        jPanel1.add(jLabelTerms);

        jCheckTerminos.setText("Aceptar Terminos y condiciones");
        jCheckTerminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTerminosActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckTerminos);

        jLabelAge.setText("Edad:");
        jPanel1.add(jLabelAge);
        jPanel1.add(jSpinnerAge);

        jButtonRegistro.setBackground(new java.awt.Color(0, 153, 0));
        jButtonRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistro.setText("Darse de alta");
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        jLabel1.setText("Sr / Sra) :");

        buttonGroupTrato.add(RadioButtonSR);
        RadioButtonSR.setText("Sr");

        buttonGroupTrato.add(RadioButtonSRA);
        RadioButtonSRA.setText("Sra");
        RadioButtonSRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSRAActionPerformed(evt);
            }
        });

        jButtonHelp.setBackground(new java.awt.Color(0, 102, 204));
        jButtonHelp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHelp.setText("Click si necesitas ayuda");
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RadioButtonSR, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioButtonSRA))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHelp))
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonSRA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RadioButtonSR))
                        .addGap(221, 221, 221)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            String name = jTextFieldUser.getText();
            String passwd1 = jPassField1.getText();
            String passwd2 = jPassField2.getText();

            SimpleDateFormat simpledate = new SimpleDateFormat("dd-MM-yyyy");
            String dateRegister = simpledate.format(jDateRegistro.getDate());
            String treatment = buttonGroupTrato.getSelection().getActionCommand();;
            String birthPlace = jComboBoxLocalidad.getSelectedItem().toString();

            int ageUser = (Integer) jSpinnerAge.getValue();
            JOptionPane.showMessageDialog(this, "Se ha registrado a las: " + dateRegister, "", JOptionPane.INFORMATION_MESSAGE);
            LogicaCliente.agregarCliente(new client(treatment, name, passwd1, birthPlace, dateRegister, ageUser, pathImage));
            jButtonRegistro.setEnabled(true);
            dispose();
            System.out.println("Funciona dar de alta");
        }
    }//GEN-LAST:event_jButtonRegistroActionPerformed

    private void jPassField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassField2ActionPerformed

    private void RadioButtonSRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonSRAActionPerformed

    private void jButtonImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImgActionPerformed
        // TODO add your handling code here:
        JFileChooser elegirImagen = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("All Pic", "png", "jpg");
        elegirImagen.addChoosableFileFilter(filter);

        int opcion = elegirImagen.showOpenDialog(null);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            File archivo = elegirImagen.getSelectedFile();
            pathImage = archivo.getAbsolutePath();
            JOptionPane.showMessageDialog(this, pathImage);
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado una imagen.", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonImgActionPerformed

    private void jCheckTerminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTerminosActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, "¡Esta seguro de aceptar los terminos y condiciones!", "", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            jCheckTerminos.setSelected(true);
            jButtonRegistro.setEnabled(true);
        } else {
            jCheckTerminos.setSelected(false);
            jButtonRegistro.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckTerminosActionPerformed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        // TODO add your handling code here:
        String formato = "--------------------------------------------------------------------------------------------------------------------------------\n + 1. Seleccione el tratamineto deseado presionando sobre el circulito. \n + 2. Introduzca su nombre por favor. \n + 3. Introduzca una contraseña segura por favor \n + 4 Introduzca de nuevo la contraseña anterior \n + 5 Seleccione la provincia donde reside actualmente. \n + 6 Marque la casilla de condiciones dando consentimiento con un click. \n + 7 Selecciona tu edad \n --------------------------------------------------------------------------------------------------------------------------------";
        JOptionPane.showMessageDialog(this, formato, "", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButtonHelpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButtonSR;
    private javax.swing.JRadioButton RadioButtonSRA;
    private javax.swing.ButtonGroup buttonGroupTrato;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonImg;
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JCheckBox jCheckTerminos;
    private javax.swing.JComboBox<String> jComboBoxLocalidad;
    private com.toedter.calendar.JDateChooser jDateRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelBirth;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelPass2;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelTerms;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassField1;
    private javax.swing.JPasswordField jPassField2;
    private javax.swing.JSpinner jSpinnerAge;
    private javax.swing.JTextField jTextFieldUser;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables

}
