/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inicioSesion.gui;
import inicioSesion.dto.client;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author estudiante
 */
public class PantallaSecundaria extends javax.swing.JFrame {
    private client Pclient;
    private String pathImage;

    /**
     * Creates new form PantallaSecundaria
     */
    public PantallaSecundaria(client Nclient) {
        initComponents();
        Pclient = Nclient;
        LabelUser.setText(Pclient.getTrato() + " " + Pclient.getUsuario());        
        pathImage = Pclient.getPathImage();
        LabelRegister.setText(Pclient.getFechaRegistro());
        LabelBirth.setText(Pclient.getNacimiento());
        LabelAge.setText(String.valueOf(Pclient.getEdad()));
        setLabelImage();
    }
    
     private void setLabelImage(){
        
        //ESTE CODIGO SE IMPLEMENTA CUANDO CREE EL JLABELIMAGE EN DESIGN.
        Image img1 = Toolkit.getDefaultToolkit().createImage(pathImage);
        img1 = img1.getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img2 = new ImageIcon(img1);
        jLabelImage.setIcon(img2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUser = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jLabelBirth = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        LabelTratement = new javax.swing.JLabel();
        LabelUser = new javax.swing.JLabel();
        LabelRegister = new javax.swing.JLabel();
        LabelBirth = new javax.swing.JLabel();
        LabelAge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelUser.setText("Nombre:");

        jLabelRegister.setText("F. Registro:");

        jLabelBirth.setText("F. Nacimiento:");

        jLabelAge.setText("Edad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUser)
                    .addComponent(jLabelRegister)
                    .addComponent(jLabelBirth)
                    .addComponent(jLabelAge))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAge)
                    .addComponent(LabelBirth)
                    .addComponent(LabelRegister)
                    .addComponent(LabelUser))
                .addGap(50, 50, 50)
                .addComponent(LabelTratement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUser)
                            .addComponent(LabelUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTratement)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRegister)
                            .addComponent(LabelRegister))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelBirth)
                            .addComponent(jLabelBirth))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAge)
                            .addComponent(LabelAge)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAge;
    private javax.swing.JLabel LabelBirth;
    private javax.swing.JLabel LabelRegister;
    private javax.swing.JLabel LabelTratement;
    private javax.swing.JLabel LabelUser;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelBirth;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabelUser;
    // End of variables declaration//GEN-END:variables
}
